ayano-python/myapp/urls.py
from django.urls import path

from . import views

app_name = "myapp"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

ayano-python/myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('portfolio.urls')),
    path('survey/', include('myapp.urls')),
    path("admin/", admin.site.urls),
]

ayano-python/portfolio/urls.py
from django.urls import path

from . import views

app_name = "portfolio"
urlpatterns = [
    path('', views.index, name='index'),
]

ayano-python/myapp/models.py
from django.db import models


class Question(models.Model):
    text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    

ayano-python/portfolio/models.py
from django.db import models

# Create your models here.

ayano-python/myapp/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from .models import Question, Choice


def index(request):
    latest_questions = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_questions': latest_questions}
    return render(request, 'myapp/index.html', context)


def detail(request, question_id):
    question = Question.objects.get(pk=question_id)
    return render(request, 'myapp/detail.html', {'question': question})


def results(request, question_id):
    question = Question.objects.get(pk=question_id)
    return render(request, 'myapp/results.html', {'question': question})


def vote(request, question_id):
    question = Question.objects.get(pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'myapp/detail.html', {
            'question': question,
            'error_message': "回答を選択していません"
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('myapp:results', args=(question.id,)))

ayano-python/portfolio/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'portfolio/index.html',)

ayano-python/myapp/templates/myapp/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
    <style>
        @font-face {
            font-family: "はれのそら明朝";
            src: url('https://cdn.leafscape.be/Harenosora/harenosora_web.woff2') format("woff2");
            font-weight: normal;
            font-style: normal;
            unicode-range: U+2E80-2FFFF;
        }

        body {
            font-family: "はれのそら明朝", serif;
            background-image: url("{% static 'image/hana.png' %}");
            background-position: center;
            background-size: cover;
            height: 100vh;
        }

        main > div {
            background-color: white;
            height: 100vh;
        }
    </style>
</head>
<body>
    <main>
        <div class="container pt-3">
            <h1 class="border-bottom pb-1 mb-3">{% block header %}{% endblock %}</h1>
            <div class="container">
                {% block content %}{% endblock %}
            </div>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

ayano-python/myapp/templates/myapp/detail.html
{% extends "myapp/base.html" %}
{% block title %}アンケート - {{ question.text }}{% endblock %}
{% block header %}{{ question.text }}{% endblock %}
{% block content %}
    <form action="{% url 'myapp:vote' question.id %}" method="post">
        {% csrf_token %}
        <div class="list-group list-group-flush">
            {% for choice in question.choice_set.all %}
                <label class="list-group-item list-group-item-action">
                    <input class="form-check-input" type="radio" name="choice" value="{{ choice.id }}">
                    {{ choice.text }}
                </label>
            {% endfor %}
        </div>
        <input type="submit" value="投票する" class="btn btn-info text-white mt-2">
    </form>
    <a href="{% url 'myapp:index' %}">別の質問に投票する</a>
{% endblock %}

ayano-python/myapp/templates/myapp/index.html
{% extends "myapp/base.html" %}
{% block title %}アンケート{% endblock %}
{% block header %}アンケート{% endblock %}
{% block content %}
    <div class="list-group list-group-flush">
        {% for question in latest_questions %}
            <a class="list-group-item list-group-item-action" href="{% url 'myapp:detail' question.id %}">
                {{ question.text }}
            </a>
        {% endfor %}
    </div>
{% endblock %}

ayano-python/myapp/templates/myapp/results.html
{% extends "myapp/base.html" %}
{% block title %}アンケート - 投票結果{% endblock %}
{% block header %}投票結果{% endblock %}
{% block content %}
    <p>{{ question.text }}</p>
    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.text }} -- {{ choice.votes }}票</li>
    {% endfor %}
    </ul>
    <a href="{% url 'myapp:index' %}">別の質問に投票する</a>
{% endblock %}

ayano-python/portfolio/templates/portfolio/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Ayano Nabeshima</title>
    <style>
      @font-face {
        font-family: "はれのそら明朝";
        src: url('https://cdn.leafscape.be/Harenosora/harenosora_web.woff2') format("woff2");
        font-weight: normal;
        font-style: normal;
        unicode-range: U+2E80-2FFFF;
      }

      body {
        font-family: "はれのそら明朝", serif;
      }

      .introduction {
        background-image: url("{% static 'image/header.jpg' %}");
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
      }

      .grass {
        backdrop-filter: blur(5px) brightness(120%);
      }

      .comment {
        margin: 0;
        font-size: 18px;
      }
    </style>
  </head>
  <body>
    <main>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#about_me">
                  <img src="{% static 'image/icon.png' %}" style="width: 2em; height: auto;" alt="">
                  About me
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#learning">
                  <img src="{% static 'image/hon.png' %}" style="width: 2em; height: auto;" alt="">
                  勉強中のもの
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#others">
                  <img src="{% static 'image/kira.png' %}" style="width: 2em; height: auto;" alt="">
                  その他
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>


      <div class="introduction mb-4">
        <div class="p-4">
          <div class="container p-4 rounded-3 grass">
            <h1 class="display-6 fw-bold">Ayano's Portfolio Site</h1>
            <p class="col-md-8 fs-5">Thank you for visiting my website.</p>
          </div>
        </div>
      </div>

      <div id="about_me" class="container px-5 py-3">
        <div class="col d-flex align-items-start mb-5">
          <div class="flex-shrink-0 me-3">
            <img src="{% static 'image/icon.png' %}" style="width: 5em; height: auto">
          </div>
          <div>
            <h2>About me</h2>
            <p class="comment">
              ポートフォリオサイトへお越しいただきありがとうございます。<br>
              鍋嶋彩乃と申します。<br>
              IT企業で働くために日々奮闘中です。<br>
              システム開発を通して、働きやすい会社を増やすことが目標です。
            </p>
          </div>
        </div>
        
        <div id="learning" class="col d-flex align-items-start mb-5">
          <div class="flex-shrink-0 me-3">
            <img src="{% static 'image/hon.png' %}" style="width: 5em; height: auto">
          </div>
          <div>
            <h2>勉強中のもの</h2>
            <p class="comment">
              Python / Django / HTML ……<br>
              参考書籍: Python Djamgo3 超入門  掌田津那乃 等……
            </p>
          </div>
        </div>

        <div id="others" class="col d-flex align-items-start mb-5">
          <div class="flex-shrink-0 me-3">
            <img src="{% static 'image/kira.png' %}" style="width: 5em; height: auto">
          </div>
          <div>
            <h2>その他</h2>
            <p class="comment mb-2">
              勉強している中で制作したものです。<br>
              よろしければご覧ください。
            </p>
            <div class="border border-2 bg-light bg-gradient rounded-3 p-3">
              <h5>アンケートサイト</h5>
              <p>Djangoの学習中での成果物です。
              </p>
              <a class="btn btn-outline-primary" href="{% url 'myapp:index' %}">≫ アンケートサイトはこちら</a>
            </div>
          </div>
        </div>
      </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>